export const ERRORS = {
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    ALREADY_EXISTS: 'ALREADY_EXISTS',
    INCOMPLETE_DATA: 'INCOMPLETE_DATA',
    BAD_REQUEST: 'BAD_REQUEST'
} as const;
